import mockSingleGym from "./mockSingleGym";
import mockEmployeeList from "./mockEmployeeList";

const mockCurrentBoulderDistribution = [
  {
    id: 1,
    gymId: 1,
    grade: "V10",
    color: "White",
    setterId: mockEmployeeList[2].id,
    setter: mockEmployeeList[2].placardName,
    holds: null,
    style: null,
    sectionId: 1,
    dateSet: "2023-08-15",
    position: null,
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 2,
    gymId: 1,
    grade: "V2",
    color: "Green",
    setterId: mockEmployeeList[1].id,
    setter: mockEmployeeList[1].placardName,
    holds: null,
    style: null,
    sectionId: 1,
    dateSet: "2023-08-15",
    position: null,
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 3,
    gymId: 1,
    grade: "V5",
    color: "Red",
    setterId: mockEmployeeList[0].id,
    setter: mockEmployeeList[0].placardName,
    holds: null,
    style: null,
    sectionId: 1,
    dateSet: "2023-08-15",
    position: null,
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 4,
    gymId: 1,
    grade: "VB",
    color: "Black",
    setterId: mockEmployeeList[1].id,
    setter: mockEmployeeList[1].placardName,
    holds: null,
    style: null,
    sectionId: 1,
    dateSet: "2023-08-15",
    position: null,
    deletedAt: null,
    gym: mockSingleGym,
  },
];

export default mockCurrentBoulderDistribution;