import mockSingleGym from "./mockSingleGym";
import mockEmployeeList from "./mockEmployeeList";

const mockCurrentRopeDistribution = [
  {
    id: 1,
    gymId: 1,
    station: '1',
    sectionId: 1,
    ropeStyle: 'Top Rope Only',
    grade: '5.11-',
    color: 'Purple',
    setterId: mockEmployeeList[0].id,
    setter: mockEmployeeList[0].placardName,
    climbName: '',
    holds: '',
    style: '',
    dateSet: '2023-05-24',
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 2,
    gymId: 1,
    station: '1',
    sectionId: 2,
    ropeStyle: 'TR/Lead',
    grade: '5.8',
    color: 'Red',
    setterId: mockEmployeeList[1].id,
    setter: mockEmployeeList[1].placardName,
    climbName: '',
    holds: '',
    style: '',
    dateSet: '2023-05-24',
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 3,
    gymId: 1,
    station: '1',
    sectionId: 3,
    ropeStyle: 'Lead Only',
    grade: '5.12-',
    color: 'Blue',
    setterId: mockEmployeeList[0].id,
    setter: mockEmployeeList[0].placardName,
    climbName: '',
    holds: '',
    style: '',
    dateSet: '2023-05-24',
    deletedAt: null,
    gym: mockSingleGym,
  },
  {
    id: 4,
    gymId: 1,
    station: '1',
    sectionId: 3,
    ropeStyle: 'Lead Only',
    grade: '5.10+',
    color: 'Green',
    setterId: mockEmployeeList[2].id,
    setter: mockEmployeeList[2].placardName,
    climbName: '',
    holds: '',
    style: '',
    dateSet: '2023-05-24',
    deletedAt: null,
    gym: mockSingleGym,
  },
];

export default mockCurrentRopeDistribution;